name: Remote Server Integration Test

on: [push]

jobs:
  build-and-test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Testing the three major OS environments
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y sshpass build-essential cmake

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install sshpass cmake colima docker
          
          ## colima setting
          brew services start colima
          # Force stop and delete the broken instance
          colima delete -f
          rm -rf ~/.colima ~/.lima
          colima start --driver qemu --cpu 2 --memory 4
          # Point the docker CLI to the colima socket
          sudo ln -sf ~/.colima/default/docker.sock /var/run/docker.sock

      - name: Configure and Build
        run: cmake -B cmake-build-debug -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build cmake-build-debug

      - name: Execute Tests
        run: |
          cd cmake-build-debug
          ctest --extra-verbose

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: rs-${{ matrix.os }}
          path: cmake-build-debug/rs*